services:
  python:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bottlesite_new_Santiago
    ports:
      - 80:80
    volumes:
      - ./:/app
